package com.http.httpclientproj;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HttpClient implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public HttpClient() {
    }




}